// <auto-generated />
using System;
using Datamigratie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Datamigratie.Data.Migrations
{
    [DbContext(typeof(DatamigratieDbContext))]
    [Migration("20250917082645_ZaaktypeMapping")]
    partial class ZaaktypeMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Datamigratie.Data.Entities.ZaaktypeMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DetZaaktypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("det_zaaktype_id");

                    b.Property<string>("OzZaaktypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oz_zaaktype_id");

                    b.HasKey("Id")
                        .HasName("pk_zaaktype_mapping");

                    b.HasIndex("DetZaaktypeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Mapping_DetZaaktypeId_Unique");

                    b.ToTable("zaaktype_mapping", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
