// <auto-generated />
using System;
using Datamigratie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Datamigratie.Data.Migrations
{
    [DbContext(typeof(DatamigratieDbContext))]
    [Migration("20260128100328_RenameGlobalConfigurationToRsinConfiguration")]
    partial class RenameGlobalConfigurationToRsinConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Datamigratie.Data.Entities.DocumentstatusMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetDocumentstatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OzDocumentstatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DetDocumentstatus")
                        .IsUnique()
                        .HasDatabaseName("IX_DocumentstatusMapping_DetDocumentstatus_Unique");

                    b.ToTable("DocumentstatusMappings");
                });

            modelBuilder.Entity("Datamigratie.Data.Entities.Migration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetZaaktypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FailedRecords")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessedRecords")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuccessfulRecords")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalRecords")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DetZaaktypeId");

                    b.HasIndex("Status");

                    b.ToTable("Migrations");
                });

            modelBuilder.Entity("Datamigratie.Data.Entities.MigrationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetZaaknummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text");

                    b.Property<string>("ErrorTitle")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<int>("MigrationId")
                        .HasColumnType("integer");

                    b.Property<string>("OzZaaknummer")
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MigrationId");

                    b.ToTable("MigrationRecords");
                });

            modelBuilder.Entity("Datamigratie.Data.Entities.ResultaattypeMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DetResultaattypeNaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OzResultaattypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ZaaktypenMappingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZaaktypenMappingId", "DetResultaattypeNaam")
                        .IsUnique()
                        .HasDatabaseName("IX_ResultaattypeMapping_ZaaktypenMappingId_DetResultaattypeNaam_Unique");

                    b.ToTable("ResultaattypeMappings");
                });

            modelBuilder.Entity("Datamigratie.Data.Entities.RsinConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Rsin")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("Id");

                    b.ToTable("RsinConfigurations");
                });

            modelBuilder.Entity("Datamigratie.Data.Entities.StatusMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetStatusNaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OzStatustypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ZaaktypenMappingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZaaktypenMappingId", "DetStatusNaam")
                        .IsUnique()
                        .HasDatabaseName("IX_StatusMapping_ZaaktypenMappingId_DetStatusNaam_Unique");

                    b.ToTable("StatusMappings");
                });

            modelBuilder.Entity("Datamigratie.Data.Entities.ZaaktypenMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DetZaaktypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OzZaaktypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetZaaktypeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Mapping_DetZaaktypeId_Unique");

                    b.ToTable("Mappings");
                });

            modelBuilder.Entity("Datamigratie.Data.Entities.MigrationRecord", b =>
                {
                    b.HasOne("Datamigratie.Data.Entities.Migration", "Migration")
                        .WithMany()
                        .HasForeignKey("MigrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Migration");
                });

            modelBuilder.Entity("Datamigratie.Data.Entities.ResultaattypeMapping", b =>
                {
                    b.HasOne("Datamigratie.Data.Entities.ZaaktypenMapping", "ZaaktypenMapping")
                        .WithMany()
                        .HasForeignKey("ZaaktypenMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZaaktypenMapping");
                });

            modelBuilder.Entity("Datamigratie.Data.Entities.StatusMapping", b =>
                {
                    b.HasOne("Datamigratie.Data.Entities.ZaaktypenMapping", "ZaaktypenMapping")
                        .WithMany()
                        .HasForeignKey("ZaaktypenMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZaaktypenMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
