{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "datamigratie.fullname" . }}-migrations-{{ .Release.Revision }}
  labels:
    {{- include "datamigratie.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "datamigratie.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "datamigratie.serviceAccountName" . }}
      {{- if .Values.migrations.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.migrations.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-migrations
        image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
        envFrom:
          - secretRef:
              name: {{ .Values.existingSecret | default (include "datamigratie.fullname" .) }}
          - configMapRef:
              name: {{ include "datamigratie.fullname" . }}
    {{- if .Values.postgresql.enabled }}
      initContainers:
      - name: "{{ .Chart.Name }}-wait-for-postgresql"
        image: "{{ .Values.initContainers.waitFor.image.repository }}:{{ .Values.initContainers.waitFor.image.tag }}"
        imagePullPolicy: {{ .Values.initContainers.waitFor.image.pullPolicy }}
        args:
        - "service"
        - "{{ .Release.Name }}-postgresql"
    {{- end }}
      restartPolicy: {{ .Values.migrations.restartPolicy }}
{{- end }}
